### ISSUE TITLE
error: environment variable not found

### ISSUE THREAD

**Issue by zeritonius** [jlyonsmith/bookmark-exporter#1]
First of all, this is a project I'm very interested in and I thank you so much for creating it!

I successfully built it, but when I ran it, on Windows 10 (Home Edition, Version 10.0.19045.4780) I couldn't export anything.
I got the error: `environment variable not found`
I was wondering if you could make that message more suggestive, as I'm not sure what variable was not found

On Firefox, I have several profiles. Is it possible to export a certain one of them? Or will export is only the main?

If I may make some suggestions:
1. When I type bookmark-exporter.exe, nothing happen. I would like it to display the --help automatically

2. When I built it, I got this error:
`note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'`
I fixed by adding setting the LIB environmental variable as following
`set LIB=%LIB%;"C:\mylibs", `
then I put sqlite3.lib into c:\mylibs

3. I would like an example, please, of what the extension of the export file will be. I tried out.json or out.sqlite,
but I'm not sure if those were the right extension.

Thank you again for this opportunity to export from command line!
![out](https://github.com/user-attachments/assets/61a783d3-3567-4862-967e-d41f158eadc0)

**Comment by jlyonsmith** [comment]
Hey, thanks for the feedback.  

The error message is because there is no `HOME` environment variable on Windows.  I pushed a change using the `dirs` crate which should do the right thing on Windows.  _However_ the bookmark files are in different directories on Windows, so it still won't work.  I don't have access to a Windows box and don't plan too get one.  Happy to take a pull request if you want to add the support.

You can read about where Chrome stores bookmarks [here](https://www.howtogeek.com/819125/where-are-google-chrome-bookmarks-stored-on-my-computer/) and where Firefox stores bookmarks [here](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data).   Profiles are just stored in separate directories for both I believe.  You could add a flag to specify the profile you want.  But then I think you'd have to add an option to list profile names for usability.

On a Mac the `sqlite3.lib` is picked up automatically, so you don't hit that build issue that you do on Windows.

I fixed the program to output help when there are no arguments.  

There is no file format for the output.  It's just the bookmark name, then the bookmark URL on separate lines plain old vanilla text.
